"""
Badge system seed data
Comprehensive badge collection across all categories and tiers
"""

from models import BadgeCategory, BadgeTier

BADGES = [
    # ==================== CARBON REDUCTION BADGES ====================
    {
        "name": "Carbon Warrior Bronze",
        "description": "Saved 100 kg of CO₂",
        "category": BadgeCategory.CARBON,
        "tier": BadgeTier.BRONZE,
        "icon": "🌱",
        "color": "#CD7F32",
        "criteria_type": "carbon_saved",
        "criteria_value": 100.0,
        "sort_order": 1,
        "can_order_physical": True,
        "physical_cost": 5.00,
    },
    {
        "name": "Carbon Warrior Silver",
        "description": "Saved 500 kg of CO₂",
        "category": BadgeCategory.CARBON,
        "tier": BadgeTier.SILVER,
        "icon": "🌿",
        "color": "#C0C0C0",
        "criteria_type": "carbon_saved",
        "criteria_value": 500.0,
        "sort_order": 2,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Carbon Warrior Gold",
        "description": "Saved 1,000 kg of CO₂",
        "category": BadgeCategory.CARBON,
        "tier": BadgeTier.GOLD,
        "icon": "🌳",
        "color": "#FFD700",
        "criteria_type": "carbon_saved",
        "criteria_value": 1000.0,
        "sort_order": 3,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },
    {
        "name": "Carbon Champion Platinum",
        "description": "Saved 5,000 kg of CO₂",
        "category": BadgeCategory.CARBON,
        "tier": BadgeTier.PLATINUM,
        "icon": "🌲",
        "color": "#E5E4E2",
        "criteria_type": "carbon_saved",
        "criteria_value": 5000.0,
        "sort_order": 4,
        "can_order_physical": True,
        "physical_cost": 25.00,
    },
    {
        "name": "Carbon Hero Diamond",
        "description": "Saved 10,000 kg of CO₂",
        "category": BadgeCategory.CARBON,
        "tier": BadgeTier.DIAMOND,
        "icon": "🏆",
        "color": "#B9F2FF",
        "criteria_type": "carbon_saved",
        "criteria_value": 10000.0,
        "sort_order": 5,
        "can_order_physical": True,
        "physical_cost": 50.00,
    },

    # ==================== PLASTIC REDUCTION BADGES ====================
    {
        "name": "Plastic Fighter Bronze",
        "description": "Prevented 10 kg of plastic waste",
        "category": BadgeCategory.PLASTIC,
        "tier": BadgeTier.BRONZE,
        "icon": "♻️",
        "color": "#CD7F32",
        "criteria_type": "plastic_saved",
        "criteria_value": 10.0,
        "sort_order": 6,
        "can_order_physical": True,
        "physical_cost": 5.00,
    },
    {
        "name": "Plastic Fighter Silver",
        "description": "Prevented 50 kg of plastic waste",
        "category": BadgeCategory.PLASTIC,
        "tier": BadgeTier.SILVER,
        "icon": "🔄",
        "color": "#C0C0C0",
        "criteria_type": "plastic_saved",
        "criteria_value": 50.0,
        "sort_order": 7,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Plastic Fighter Gold",
        "description": "Prevented 100 kg of plastic waste",
        "category": BadgeCategory.PLASTIC,
        "tier": BadgeTier.GOLD,
        "icon": "🌊",
        "color": "#FFD700",
        "criteria_type": "plastic_saved",
        "criteria_value": 100.0,
        "sort_order": 8,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },

    # ==================== WATER CONSERVATION BADGES ====================
    {
        "name": "Water Saver Bronze",
        "description": "Conserved 5,000 liters of water",
        "category": BadgeCategory.WATER,
        "tier": BadgeTier.BRONZE,
        "icon": "💧",
        "color": "#CD7F32",
        "criteria_type": "water_saved",
        "criteria_value": 5000.0,
        "sort_order": 9,
        "can_order_physical": True,
        "physical_cost": 5.00,
    },
    {
        "name": "Water Saver Silver",
        "description": "Conserved 20,000 liters of water",
        "category": BadgeCategory.WATER,
        "tier": BadgeTier.SILVER,
        "icon": "💦",
        "color": "#C0C0C0",
        "criteria_type": "water_saved",
        "criteria_value": 20000.0,
        "sort_order": 10,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Water Guardian Gold",
        "description": "Conserved 50,000 liters of water",
        "category": BadgeCategory.WATER,
        "tier": BadgeTier.GOLD,
        "icon": "🌈",
        "color": "#FFD700",
        "criteria_type": "water_saved",
        "criteria_value": 50000.0,
        "sort_order": 11,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },

    # ==================== WASTE REDUCTION BADGES ====================
    {
        "name": "Zero Waste Beginner",
        "description": "Started your waste reduction journey",
        "category": BadgeCategory.WASTE,
        "tier": BadgeTier.BRONZE,
        "icon": "🗑️",
        "color": "#CD7F32",
        "criteria_type": "waste_pledges",
        "criteria_value": 1.0,
        "sort_order": 12,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Compost Champion",
        "description": "Committed to composting for 90 days",
        "category": BadgeCategory.WASTE,
        "tier": BadgeTier.SILVER,
        "icon": "🌱",
        "color": "#C0C0C0",
        "criteria_type": "compost_days",
        "criteria_value": 90.0,
        "sort_order": 13,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },

    # ==================== ECOSYSTEM RESTORATION BADGES ====================
    {
        "name": "Tree Hugger",
        "description": "Planted or supported planting of 10 tree equivalents",
        "category": BadgeCategory.ECOSYSTEM,
        "tier": BadgeTier.BRONZE,
        "icon": "🌳",
        "color": "#CD7F32",
        "criteria_type": "trees_equivalent",
        "criteria_value": 10.0,
        "sort_order": 14,
        "can_order_physical": True,
        "physical_cost": 5.00,
    },
    {
        "name": "Forest Creator",
        "description": "Planted or supported planting of 50 tree equivalents",
        "category": BadgeCategory.ECOSYSTEM,
        "tier": BadgeTier.SILVER,
        "icon": "🌲",
        "color": "#C0C0C0",
        "criteria_type": "trees_equivalent",
        "criteria_value": 50.0,
        "sort_order": 15,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Ecosystem Guardian",
        "description": "Achieved 500 ecosystem restoration points",
        "category": BadgeCategory.ECOSYSTEM,
        "tier": BadgeTier.GOLD,
        "icon": "🦋",
        "color": "#FFD700",
        "criteria_type": "ecosystem_points",
        "criteria_value": 500.0,
        "sort_order": 16,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },

    # ==================== ENERGY CONSERVATION BADGES ====================
    {
        "name": "Energy Saver",
        "description": "Committed to 3 energy-saving actions",
        "category": BadgeCategory.ENERGY,
        "tier": BadgeTier.BRONZE,
        "icon": "⚡",
        "color": "#CD7F32",
        "criteria_type": "energy_pledges",
        "criteria_value": 3.0,
        "sort_order": 17,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Renewable Champion",
        "description": "Switched to renewable energy",
        "category": BadgeCategory.ENERGY,
        "tier": BadgeTier.GOLD,
        "icon": "☀️",
        "color": "#FFD700",
        "criteria_type": "renewable_pledge",
        "criteria_value": 1.0,
        "sort_order": 18,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },

    # ==================== COMMUNITY BADGES ====================
    {
        "name": "Community Starter",
        "description": "Joined an organization or group",
        "category": BadgeCategory.COMMUNITY,
        "tier": BadgeTier.BRONZE,
        "icon": "👥",
        "color": "#CD7F32",
        "criteria_type": "org_joined",
        "criteria_value": 1.0,
        "sort_order": 19,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Community Builder",
        "description": "Created an organization",
        "category": BadgeCategory.COMMUNITY,
        "tier": BadgeTier.SILVER,
        "icon": "🏘️",
        "color": "#C0C0C0",
        "criteria_type": "org_created",
        "criteria_value": 1.0,
        "sort_order": 20,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Influencer",
        "description": "10 people joined through your organization",
        "category": BadgeCategory.COMMUNITY,
        "tier": BadgeTier.GOLD,
        "icon": "🌟",
        "color": "#FFD700",
        "criteria_type": "members_recruited",
        "criteria_value": 10.0,
        "sort_order": 21,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },
    {
        "name": "Movement Leader",
        "description": "50 people joined through your organization",
        "category": BadgeCategory.COMMUNITY,
        "tier": BadgeTier.PLATINUM,
        "icon": "👑",
        "color": "#E5E4E2",
        "criteria_type": "members_recruited",
        "criteria_value": 50.0,
        "sort_order": 22,
        "can_order_physical": True,
        "physical_cost": 25.00,
    },

    # ==================== COMMITMENT BADGES ====================
    {
        "name": "First Step",
        "description": "Made your first pledge",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.BRONZE,
        "icon": "🎯",
        "color": "#CD7F32",
        "criteria_type": "pledges_made",
        "criteria_value": 1.0,
        "sort_order": 23,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Committed",
        "description": "Completed 5 pledges",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.SILVER,
        "icon": "✅",
        "color": "#C0C0C0",
        "criteria_type": "pledges_completed",
        "criteria_value": 5.0,
        "sort_order": 24,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Dedicated",
        "description": "Completed 20 pledges",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.GOLD,
        "icon": "💪",
        "color": "#FFD700",
        "criteria_type": "pledges_completed",
        "criteria_value": 20.0,
        "sort_order": 25,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },
    {
        "name": "Unstoppable",
        "description": "Completed 50 pledges",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.PLATINUM,
        "icon": "🔥",
        "color": "#E5E4E2",
        "criteria_type": "pledges_completed",
        "criteria_value": 50.0,
        "sort_order": 26,
        "can_order_physical": True,
        "physical_cost": 25.00,
    },
    {
        "name": "Week Warrior",
        "description": "Maintained a 7-day streak",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.BRONZE,
        "icon": "📅",
        "color": "#CD7F32",
        "criteria_type": "streak_days",
        "criteria_value": 7.0,
        "sort_order": 27,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Month Master",
        "description": "Maintained a 30-day streak",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.SILVER,
        "icon": "🗓️",
        "color": "#C0C0C0",
        "criteria_type": "streak_days",
        "criteria_value": 30.0,
        "sort_order": 28,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
    {
        "name": "Consistency King/Queen",
        "description": "Maintained a 100-day streak",
        "category": BadgeCategory.COMMITMENT,
        "tier": BadgeTier.GOLD,
        "icon": "⭐",
        "color": "#FFD700",
        "criteria_type": "streak_days",
        "criteria_value": 100.0,
        "sort_order": 29,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },

    # ==================== MILESTONE BADGES ====================
    {
        "name": "Earth Day Participant",
        "description": "Made a pledge on Earth Day",
        "category": BadgeCategory.MILESTONE,
        "tier": BadgeTier.BRONZE,
        "icon": "🌍",
        "color": "#CD7F32",
        "criteria_type": "earth_day_pledge",
        "criteria_value": 1.0,
        "sort_order": 30,
        "can_order_physical": True,
        "physical_cost": 5.00,
    },
    {
        "name": "New Year, New Planet",
        "description": "Made a pledge on New Year's Day",
        "category": BadgeCategory.MILESTONE,
        "tier": BadgeTier.BRONZE,
        "icon": "🎉",
        "color": "#CD7F32",
        "criteria_type": "new_year_pledge",
        "criteria_value": 1.0,
        "sort_order": 31,
        "can_order_physical": False,
        "physical_cost": 0.0,
    },
    {
        "name": "Early Adopter",
        "description": "Joined in the first month",
        "category": BadgeCategory.MILESTONE,
        "tier": BadgeTier.GOLD,
        "icon": "🚀",
        "color": "#FFD700",
        "criteria_type": "early_adopter",
        "criteria_value": 1.0,
        "sort_order": 32,
        "can_order_physical": True,
        "physical_cost": 15.00,
    },
    {
        "name": "First 100",
        "description": "One of the first 100 users",
        "category": BadgeCategory.MILESTONE,
        "tier": BadgeTier.DIAMOND,
        "icon": "💎",
        "color": "#B9F2FF",
        "criteria_type": "user_number",
        "criteria_value": 100.0,
        "sort_order": 33,
        "can_order_physical": True,
        "physical_cost": 50.00,
    },
    {
        "name": "Story Teller",
        "description": "Shared your success story",
        "category": BadgeCategory.MILESTONE,
        "tier": BadgeTier.SILVER,
        "icon": "📖",
        "color": "#C0C0C0",
        "criteria_type": "story_shared",
        "criteria_value": 1.0,
        "sort_order": 34,
        "can_order_physical": True,
        "physical_cost": 10.00,
    },
]
