"""
Seed data for environmental actions based on research
All impact measurements are scientifically sourced
"""

from models import EnvironmentalAction, ImpactCategory, FrequencyType

# Carbon savings calculated per year unless otherwise noted
# Water savings calculated per year
# Plastic savings calculated per year

ENVIRONMENTAL_ACTIONS = [
    # TRANSPORTATION - High Impact
    {
        "title": "Go car-free for a year",
        "description": "Commit to living without a personal car, using public transit, biking, walking, or carpooling instead.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 2000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Living car-free can reduce carbon footprint by up to 2 tons CO2e per year (Lund University study)",
    },
    {
        "title": "Switch to an electric vehicle",
        "description": "Replace your gasoline or diesel car with an electric vehicle.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 2000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "EV adoption can reduce carbon footprint by up to 2 tons CO2e per year",
    },
    {
        "title": "Switch to a hybrid vehicle",
        "description": "Replace your traditional car with a hybrid vehicle.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 700.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Hybrid vehicles can save up to 700 kg CO2e per year",
    },
    {
        "title": "Bike instead of drive one trip per day",
        "description": "Replace one car trip each day with cycling.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 500.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Switching one trip per day to cycling can reduce carbon footprint by about 0.5 tonnes over a year",
    },
    {
        "title": "Carpool to work daily",
        "description": "Share rides to work or shopping every day.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 907.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Carpooling daily can reduce carbon footprint by about 2,000 pounds (907 kg) CO2e per year",
    },
    {
        "title": "Skip one long-haul flight",
        "description": "Avoid taking one long-distance return flight.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 2000.0,
        "frequency_type": FrequencyType.ONCE,
        "source_info": "Taking one less long-haul return flight can reduce carbon footprint by up to 2 tons CO2e",
    },

    # DIET - High Impact
    {
        "title": "Eat plant-based diet for a year",
        "description": "Commit to a fully plant-based diet, avoiding all meat and dairy products.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 800.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Plant-based diet saves about 0.8 tonnes CO2-equivalents per year (Lund University)",
    },
    {
        "title": "Go meat-free one day per week (Meatless Monday)",
        "description": "Avoid meat and dairy one day each week.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 114.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Forgoing meat and dairy one day per week saves approximately 8 pounds per day = 416 pounds (189 kg) per year, conservative estimate 114 kg",
    },
    {
        "title": "Reduce food waste by 50%",
        "description": "Plan meals, store food properly, and compost to cut food waste in half.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 250.0,
        "water_saved_liters": 1000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Reducing food waste significantly cuts methane emissions and saves resources",
    },

    # ENERGY - High Impact
    {
        "title": "Switch to 100% renewable energy at home",
        "description": "Change your home energy source to wind, solar, or other renewables.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 1500.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Renewable energy can reduce carbon footprint by up to 1.5 tons CO2e per year",
    },
    {
        "title": "Install solar panels",
        "description": "Install solar panels on your home to generate clean energy.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 1200.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Residential solar installation typically offsets 1.2+ tons CO2e annually",
    },
    {
        "title": "Reduce home heating by 1°C (2°F)",
        "description": "Lower your thermostat by one degree in winter.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 200.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Lowering thermostat saves approximately 200 kg CO2e per year",
    },
    {
        "title": "Reduce air conditioning by 1°C (2°F)",
        "description": "Raise your thermostat by one degree in summer.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 180.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Raising AC temperature saves approximately 180 kg CO2e per year",
    },
    {
        "title": "Switch all bulbs to LED",
        "description": "Replace all incandescent and CFL bulbs with LED bulbs.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 100.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "LED bulbs use 75% less energy, saving approximately 100 kg CO2e per household annually",
    },
    {
        "title": "Unplug devices when not in use",
        "description": "Eliminate vampire power by unplugging chargers and devices.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 50.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Eliminating standby power can save 50+ kg CO2e per year",
    },
    {
        "title": "Air dry clothes instead of using dryer",
        "description": "Hang dry your laundry instead of using an electric dryer.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 200.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Line drying saves approximately 200 kg CO2e per year",
    },

    # WATER CONSERVATION
    {
        "title": "Install low-flow showerhead",
        "description": "Replace standard showerhead with a WaterSense labeled 2 GPM model.",
        "category": ImpactCategory.WATER_CONSERVATION,
        "water_saved_liters": 10981.0,
        "carbon_saved_kg": 50.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Low-flow showerheads save 2,900 gallons (10,981 liters) per year for average family",
    },
    {
        "title": "Install high-efficiency toilet",
        "description": "Replace old toilet (3.5 gpf) with high-efficiency model (1.28 gpf).",
        "category": ImpactCategory.WATER_CONSERVATION,
        "water_saved_liters": 17963.0,
        "carbon_saved_kg": 40.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "High-efficiency toilets save 4,745 gallons (17,963 liters) per year",
    },
    {
        "title": "Reduce shower time by 2 minutes daily",
        "description": "Take shorter showers, saving 2 minutes each day.",
        "category": ImpactCategory.WATER_CONSERVATION,
        "water_saved_liters": 4163.0,
        "carbon_saved_kg": 20.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Reducing shower by 1 minute saves 550 gallons/year, 2 minutes = 1,100 gallons (4,163 liters)",
    },
    {
        "title": "Fix leaky faucets and toilets",
        "description": "Repair all dripping faucets and running toilets in your home.",
        "category": ImpactCategory.WATER_CONSERVATION,
        "water_saved_liters": 37854.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Fixing leaks can save 10,000+ gallons (37,854 liters) per year",
    },
    {
        "title": "Collect rainwater for garden",
        "description": "Install rain barrels to collect and use rainwater for watering plants.",
        "category": ImpactCategory.WATER_CONSERVATION,
        "water_saved_liters": 5000.0,
        "ecosystem_points": 10.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Rainwater harvesting saves thousands of liters and supports local ecosystems",
    },

    # PLASTIC REDUCTION
    {
        "title": "Use reusable water bottle",
        "description": "Stop buying single-use plastic water bottles and use a reusable one.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 7.8,
        "carbon_saved_kg": 94.4,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Prevents 156 plastic bottles annually, saves 94.4 kg CO2 per year (UK study)",
    },
    {
        "title": "Use reusable shopping bags",
        "description": "Bring your own bags for all shopping trips.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 10.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Average person uses 365+ bags per year, reusable bags prevent ~10 kg plastic waste",
    },
    {
        "title": "Say no to plastic straws",
        "description": "Refuse plastic straws or carry a reusable one.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 0.2,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Average person uses 600 straws per year, approximately 0.2 kg plastic",
    },
    {
        "title": "Buy products with minimal packaging",
        "description": "Choose products with less or no plastic packaging.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 15.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Conscious packaging choices can reduce plastic waste by 15+ kg annually",
    },
    {
        "title": "Use reusable food containers",
        "description": "Replace plastic wrap and disposable containers with reusable ones.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 5.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Reusable containers prevent significant single-use plastic waste",
    },
    {
        "title": "Choose bar soap over liquid in plastic",
        "description": "Switch to bar soap and shampoo bars instead of bottled products.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 2.5,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Bar products eliminate plastic bottle waste from personal care",
    },
    {
        "title": "Bring reusable coffee cup",
        "description": "Use your own cup for coffee shops instead of disposable cups.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 3.0,
        "carbon_saved_kg": 25.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Daily coffee cup usage creates significant waste; reusables prevent ~3 kg plastic/year",
    },

    # WASTE REDUCTION
    {
        "title": "Start composting food scraps",
        "description": "Compost all food waste instead of sending it to landfill.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 300.0,
        "ecosystem_points": 15.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Composting results in 38-84% fewer GHG emissions vs landfilling; prevents methane",
    },
    {
        "title": "Recycle properly",
        "description": "Commit to properly sorting and recycling all recyclable materials.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 150.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Proper recycling reduces carbon emissions from manufacturing new products",
    },
    {
        "title": "Buy secondhand clothing",
        "description": "Purchase used clothing instead of new items.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 200.0,
        "water_saved_liters": 20000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Fashion industry is highly polluting; secondhand reduces carbon and water use",
    },
    {
        "title": "Repair instead of replace",
        "description": "Fix broken items rather than buying new ones.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 100.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Repairing extends product life and prevents manufacturing emissions",
    },
    {
        "title": "Use cloth napkins and towels",
        "description": "Replace paper napkins and paper towels with reusable cloth.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 40.0,
        "trees_equivalent": 2.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Cloth alternatives reduce paper production and tree harvesting",
    },

    # ECOSYSTEM RESTORATION
    {
        "title": "Plant a native tree",
        "description": "Plant a native tree species appropriate for your area.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "carbon_saved_kg": 21.0,
        "ecosystem_points": 50.0,
        "trees_equivalent": 1.0,
        "water_saved_liters": 1000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "One tree absorbs ~21 kg CO2 per year and provides watershed benefits",
    },
    {
        "title": "Create a pollinator garden",
        "description": "Plant native flowers and plants that support bees, butterflies, and other pollinators.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "ecosystem_points": 40.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Pollinator gardens support biodiversity and ecosystem health",
    },
    {
        "title": "Remove invasive species from local area",
        "description": "Volunteer or personally remove invasive plants from natural areas.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "ecosystem_points": 30.0,
        "frequency_type": FrequencyType.MONTHLY,
        "source_info": "Removing invasives allows native species to thrive and restores habitat",
    },
    {
        "title": "Support rewilding projects",
        "description": "Donate to or volunteer with local ecosystem restoration projects.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "ecosystem_points": 25.0,
        "carbon_saved_kg": 50.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Ecosystem restoration generates $10 return per $1 invested (economists)",
    },
    {
        "title": "Reduce lawn area for native plants",
        "description": "Replace grass lawn with native plants and wildflowers.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "water_saved_liters": 15000.0,
        "ecosystem_points": 35.0,
        "carbon_saved_kg": 80.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Native plants require less water and support local ecosystems",
    },
    {
        "title": "Install a bird or bat house",
        "description": "Provide habitat for birds or bats in your yard.",
        "category": ImpactCategory.ECOSYSTEM_RESTORATION,
        "ecosystem_points": 15.0,
        "frequency_type": FrequencyType.ONCE,
        "source_info": "Supporting wildlife creates healthier ecosystems",
    },
    {
        "title": "Join a beach/river cleanup",
        "description": "Participate in local waterway cleanup events monthly.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 5.0,
        "ecosystem_points": 20.0,
        "frequency_type": FrequencyType.MONTHLY,
        "source_info": "Cleanups remove plastic before it breaks into microplastics",
    },

    # EVERYDAY ACTIONS - Medium Impact
    {
        "title": "Use public transportation regularly",
        "description": "Take the bus, train, or metro instead of driving.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 400.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Public transit significantly reduces per-person carbon emissions",
    },
    {
        "title": "Work from home one day per week",
        "description": "Reduce commute emissions by working remotely.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 250.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Eliminating one commute day weekly saves fuel and emissions",
    },
    {
        "title": "Eat local and seasonal food",
        "description": "Buy food grown locally and in season.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 150.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Local food reduces transportation emissions and supports local economy",
    },
    {
        "title": "Grow your own vegetables",
        "description": "Start a vegetable garden to grow some of your own food.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 75.0,
        "ecosystem_points": 20.0,
        "water_saved_liters": 2000.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Home gardens reduce food transport emissions and packaging",
    },
    {
        "title": "Wash clothes in cold water",
        "description": "Use cold water for laundry instead of hot.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 60.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Cold water washing saves energy from water heating",
    },
    {
        "title": "Meal plan to reduce waste",
        "description": "Plan weekly meals to avoid food waste.",
        "category": ImpactCategory.WASTE_REDUCTION,
        "carbon_saved_kg": 100.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Meal planning prevents food waste and associated emissions",
    },
    {
        "title": "Install a programmable thermostat",
        "description": "Use a smart thermostat to optimize heating and cooling.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 180.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Smart thermostats reduce energy use by optimizing temperature schedules",
    },
    {
        "title": "Insulate your home properly",
        "description": "Add insulation to reduce heating and cooling needs.",
        "category": ImpactCategory.ENERGY_CONSERVATION,
        "carbon_saved_kg": 400.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Proper insulation significantly reduces HVAC energy consumption",
    },
    {
        "title": "Use reusable produce bags",
        "description": "Bring mesh or cloth bags for fruits and vegetables.",
        "category": ImpactCategory.PLASTIC_REDUCTION,
        "plastic_saved_kg": 2.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Produce bags eliminate single-use plastic bag waste",
    },
    {
        "title": "Support renewable energy companies",
        "description": "Choose banks and services that invest in renewable energy.",
        "category": ImpactCategory.CARBON_REDUCTION,
        "carbon_saved_kg": 100.0,
        "frequency_type": FrequencyType.YEARLY,
        "source_info": "Financial choices influence corporate environmental practices",
    },
]
